name: Package & release Template AppImage

on:
  schedule:
    - cron: "0 0 * * *"  # Se ejecuta a las 12:00 AM UTC cada día
  workflow_dispatch:     # Permite la ejecución manual del workflow

permissions:
  contents: write  # Permitir escritura en el repositorio (incluyendo tags)
  
jobs:
  download_and_unzip:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libfuse2
          pip install --upgrade certifi
          
      - name: Download AppImage creator script
        run: |
          wget -O createAppImage.py "https://raw.githubusercontent.com/Emiliopg91/AppImage-Creator/main/createAppImage.py"
    
      - name: Download latest version
        run: |
          wget -O <customize>.tar.gz "http://<customize>"
          tar -xzvf <customize>.tar.gz
        #Do whatever you need

      - name: Build AppImage
        run: |
          version=<customize>
          python3 createAppImage.py --entrypoint=<customize> --name="<customize>" --version=$version  --icon=<customize> --description="<customize>" --desktop="./app.desktop"
                  
      - name: Upload artifacts
        if: ${{ env.IS_UPDATE == 'true' }}
        uses: actions/upload-artifact@v4
        with:
          name: appimage-files
          path: |
            ${{ env.APPIMAGE_PATH }}
            ${{ env.APPIMAGE_PATH }}.zsync

      - name: Release
        if: ${{ env.IS_UPDATE == 'true' }}
        uses: marvinpinto/action-automatic-releases@latest
        with:
          title: ${{ env.APP_VERSION }}
          automatic_release_tag: latest
          prerelease: false
          files: |
            ${{ env.APPIMAGE_PATH }}
            ${{ env.APPIMAGE_PATH }}.zsync
          repo_token: ${{ secrets.GITHUB_TOKEN }}
